
var lang =  {
              0: {0: 'Metaverse', 1: 'Метавселенная'},
              1: {0: 'Tokenomics', 1: 'Токеномика'},
              2: {0: 'Team', 1: 'Команда'},
              3: {0: 'Roadmap', 1: 'Дорожная карта'},
              4: {0: 'Play the games in our metaverse and earn cryptocurrency', 1: 'Играйте в игры в нашей метавселенной и зарабатывайте криптовалюту'},
              5: {0: 'Explore it!', 1: 'Исследуй это!'},
              6: {0: 'Active Users', 1: 'Активные пользователи'},
              7: {0: 'Downloads', 1: 'Загрузки'},
              8: {0: 'Countries', 1: 'Страны'},
              9: {0: "It\'s easy to <span>play and earn with us</span>", 1: "С нами легко <span>играть и зарабатывать</span>"},
              10: {0: 'All the distinctive gaming features revolving around our ecosystem', 1: 'Все отличительные игровые функции, вращающиеся вокруг нашей экосистемы'},
              11: {0: 'Mobile gaming is<br>always with you', 1: 'Мобильный гейминг<br>всегда с вами'},
              12: {0: 'Our games are always available on your mobile.', 1: 'Наши игры всегда доступны на вашем мобильном телефоне.'},
              13: {0: 'Earn money<br>by playing', 1: 'Зарабатывай<br>играя'},
              14: {0: 'To start playing it, you don’t need to pay anything or buy an in-game token.', 1: 'Чтобы начать играть в наши игры, вам не нужно ничего платить или покупать внутриигровой токен.'},
              15: {0: 'Game — first, crypto — later!', 1: 'Сначала — игра, потом — крипта!'},
              16: {0: 'No need to know much about the crypto to start the game. Just download, play and learn after you earn.', 1: 'Не нужно много знать о криптовалюте, чтобы начать играть. Просто скачайте, играйте и обучайтесь после того, как заработаете.'},
              17: {0: 'Token Allocation', 1: 'Распределение токенов'},
              18: {0: 'vesting schedule', 1: 'график раздачи'},
              19: {0: 'Token flow', 1: 'Движение токенов'},
              20: {0: 'User buys IGT token', 1: 'Пользователь покупает токен IGT'},
              21: {0: 'In-game purchase', 1: 'Внутриигровая покупка'},
              22: {0: 'Buying NFT', 1: 'Покупка NFT'},  
              23: {0: 'Development — 10%', 1: 'Развитие — 10%'}, 
              24: {0: 'Liquidity pool — 45%', 1: 'Пул ликвидности — 45%'}, 
              25: {0: 'Tournament pool — 45%', 1: 'Турнирный пул — 45%'}, 
              26: {0: '1 billion', 1: '1 Миллиард'}, 
              27: {0: 'To NFT creator — 5%', 1: 'Создателю NFT — 5%'}, 
              28: {0: 'Marketplace transaction fee — 2.5%', 1: 'Комиссия за транзакцию на торговой площадке — 2,5%'}, 
              29: {0: 'Tournament rewards — 2-10%', 1: 'Награды за турниры — 2-10%'}, 
              30: {0: 'Players can earn IGT by fighting on arena battles, winning tournaments, creating NFTs, selling equipment on in-game marketplace and many more.', 1: 'Игроки могут зарабатывать IGT, сражаясь на аренах, побеждая в турнирах, создавая NFT, продавая снаряжение на внутриигровом рынке и многое другое.'}, 
              31: {0: '<span>Moreover</span>, IGT is used as a governance token of iDos Games Metaverse. Our community can participate in a decentralized decision-making process regarding metaverse and its projects development using their IGTs to vote.', 1: '<span>Кроме того</span>, IGT используется в качестве токена управления iDos Games Metaverse. Наше сообщество может участвовать в децентрализованном процессе принятия решений, касающихся развития метавселенной и ее проектов, используя свои IGT для голосования.'}, 
              32: {0: 'Development of in-game NFT marketplace', 1: 'Разработка внутриигровой торговой NFT площадки'}, 
              33: {0: 'ShootGun release in the Apple Appstore', 1: 'Релиз ShootGun в Apple App Store'}, 
              34: {0: 'ShootGun release in the Apple Appstore', 1: 'Релиз ShootGun в Apple App Store'}, 
              35: {0: 'Introduction of the NFT token into the game', 1: 'Введение токена NFT в игру'}, 
              36: {0: 'Listing on major crypto exchanges', 1: 'Листинг на основных криптобиржах'}, 
              37: {0: 'Roadmap v2.0', 1: 'Дорожная карта v2.0'}, 
              38: {0: 'Core <span>team</span>', 1: 'Основная <span>команда</span>'}, 
              39: {0: 'Our <span>Advisors</span>', 1: 'Наши <span>эдвайзеры</span>'}, 
              40: {0: 'Professor of Interactive Media at University of Southern California, ex-CEO of Square Enix, Head of Publishing at Epic Games, Vice President of Digital Video & Music at Amazon', 1: 'Профессор интерактивных медиа в Университете Южной Калифорнии, бывший генеральный директор Square Enix, руководитель отдела публикаций в Epic Games, вице-президент по цифровому видео и музыке в Amazon'}, 
              41: {0: 'Strategic Advisor, Director of Ethereum competence center', 1: 'Стратегический советник, директор центра компетенций Ethereum'}, 
              42: {0: '2022 iDos Games. All rights reserved.', 1: 'iDos Games 2022 года. Все права защищены.'}, 
              43: {0: 'Token name', 1: 'Имя токена'}, 
              44: {0: 'Token supply', 1: 'Общее предложение токена'}, 
              45: {0: 'IGT usecases', 1: 'Варианты использования IGT'},   
              46: {0: '-Governance', 1: '-Управление'},   
              47: {0: '-Staking', 1: '-Стейкинг'}, 
              48: {0: '-In-game purchase', 1: '-Внутриигровая покупка'}, 
              49: {0: 'Token price', 1: 'Цена токена'}, 
              50: {0: '-Pre-seed: $0.006', 1: '-Пред-посевной: $0,006'}, 
              51: {0: '-Seed: $0.007', 1: '-Посевной: $0,007'}, 
              52: {0: '-Presale: $0.009', 1: '-Предпродажа: $0,009'}, 
              53: {0: '-Public: $0.01', 1: '-Публичный: $0,01'},   
              54: {0: 'Play To Earn,', 1: 'Играй, чтобы заработать,'}, 
              55: {0: 'Pre-seed,', 1: 'Пред-посевной,'}, 
              56: {0: 'Team,', 1: 'Команда,'}, 
              57: {0: 'Liquidity,', 1: 'Ликвидность,'}, 
              58: {0: 'Staking rewards, 15%', 1: 'Награды за стейкинг, 15%'}, 
              59: {0: 'Treasury,', 1: 'Казна,'}, 
              60: {0: 'Marketing & Advisors,<span class="proc_14_text">14%</span>', 1: 'Маркетинг и эдвайзеры,<span class="proc_14_text">14%</span>'},
              61: {0: 'Public Sale (IDO),', 1: 'Публичная продажа (IDO),'},
              62: {0: 'Seed,', 1: 'Посевной,'},
              63: {0: 'Presale,', 1: 'Предпродажа,'},
              64: {0: '2.5% (transaction fee)', 1: '2,5% (комиссия за транзакцию)'},
              65: {0: 'NFT creator', 1: 'Создатель NFT'},
              66: {0: 'Buyer 1', 1: 'Покупатель 1'},
              67: {0: 'The creator of NFT will have 97.5% (2.5% transaction fee) from the first sale of his NFTs and also 5% from each subsequent resale of his NFT on our in-game marketplace.', 1: 'Создатель NFT будет получать 97,5% (2,5% комиссии за транзакцию) с первой продажи его NFT, а также 5% с каждой последующей перепродажи его NFT на нашем внутриигровом рынке.'},
              68: {0: '<span>Thus</span>, we create an opportunity not only to play with those weapons and characters that you yourself want, but also to make money on the creation of your own piece of art.', 1: '<span>Таким образом</span>, мы создаем возможность не только играть с тем оружием и персонажами, которых вы сами хотите, но и зарабатывать на создании собственного произведения искусства.'},
              69: {0: 'Co-founder & CTO', 1: 'Соучредитель и технический директор'},
              70: {0: 'Co-founder & CEO', 1: 'Соучредитель и генеральный директор'},
              71: {0: 'CMO', 1: 'директор по маркетингу'},
              72: {0: 'Community Manager', 1: 'Менеджер сообщества'},
              73: {0: 'Graphic Designer', 1: 'Графический дизайнер'},
              74: {0: 'Concept Artist', 1: 'Концепт-художник'},
              75: {0: 'Lead Developer', 1: 'Ведущий разработчик'},
              76: {0: 'Developer', 1: 'Разработчик'},
              77: {0: '3D Modeller', 1: '3D-моделлер'},
              78: {0: 'Advisor', 1: 'Эдвайзер'},
              79: {0: 'White Paper', 1: 'Белая бумага'},
              80: {0: 'Metaverse <span>gameplay</span>', 1: 'Геймплей <span>метавселенной</span>'},
              81: {0: 'Above', 1: 'Наверх'},
              82: {0: 'IGT contract adress (BSC) <a href="https://bscscan.com/token/0xc884cf91d8b2283fabcdf899a3210746ec660197">0xc884cf91d8b2283fabcdf899a3210746ec660197</a>', 1: 'Адрес контракта IGT (BSC)  <a href="https://bscscan.com/token/0xc884cf91d8b2283fabcdf899a3210746ec660197">0xc884cf91d8b2283fabcdf899a3210746ec660197</a>'},
              83: {0: 'Released', 1: 'Вышло'},
              84: {0: 'Work in progress', 1: 'В процессе разработки'},
              85: {0: 'NFT marketplace', 1: 'Торговая площадка NFT'},
              86: {0: 'MMORPG open world', 1: 'MMORPG с открытым миром'},
              87: {0: 'Game Bank', 1: 'Игровой Банк'},
              88: {0: 'Close', 1: 'Закрыть'},
              89: {0: '', 1: ''},
              90: {0: '', 1: ''},
            }